config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :locations

  get '/info/:page' => 'info#show'

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/info_controller.rb
class InfoController < ApplicationController

  #This will render static pages by name of he page
  def show
    render template: "info/#{params[:page]}"
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location, notice: 'Location has been created.'

    else # nothing, yet end end
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  private

  def location_params
    params.require(:location).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/info/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>About</title>
</head>
<body>
<h2>About this website</h2>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ada's Shopkin Collection</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, message| %>
    <div><%= message %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/locations/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Locations Listings</title>
</head>
<body>

</body>
</html>

app/views/locations/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Locations Administration</title>
</head>
<body>
<%= form_for(@location) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <%= f.submit %>
<% end %>

</body>
</html>

app/views/locations/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Location Info</title>
</head>
<body>
<h1><%= @location.name %></h1>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ada's Shopkin Collection</title>
</head>
<body class="main_page">
<header>
  <h1>Welcome!</h1>
  <p>The best Shopkins at the best searches!</p>
</header>
<nav>
  <ul class="main_nav">
    <li>Sign In</li>
    <li>List</li>
    <li>
     <a href="/info/about">Info</a>
    <li>
      <%= link_to 'Locations', new_location_path %>

    </li>
  </ul>
</nav>
</body>
</html>